import 'server-only';
import { db } from '@/lib/db'; import { ApiError } from '@/lib/http'; import { hashPassword } from '@/lib/password'; import { databaseId } from '@/services/attachments';
const day = (value?: string) => value ? new Date(`${value}T00:00:00+09:00`) : null;
export async function listWorks() { const rows = await db().workCase.findMany({ where: { deletedAt: null }, orderBy: { updatedAt: 'desc' }, include: { _count: { select: { workCaseImagesByWorkCaseId: { where: { deletedAt: null } } } } } }); return rows.map(r => ({ id: r.id.toString(), title: r.title, slug: r.slug, category: r.category, published: r.published, updatedAt: r.updatedAt.toISOString(), imageCount: r._count.workCaseImagesByWorkCaseId })); }
export async function createWork(actor: string, input: { title: string; slug: string; category: 'FIRE_ELECTRIC'|'FIRE_CONSTRUCTION'|'FIRE_INSPECTION'|'REPAIR'|'ESTIMATE'|'ETC'; location?: string; buildingType?: string; workDate?: string; summary?: string; description: string; published: boolean }) { try { const row = await db().$transaction(async tx => { const item = await tx.workCase.create({ data: { ...input, workDate: day(input.workDate), publishedAt: input.published ? new Date() : null, createdByAdminId: BigInt(actor) } }); await tx.adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'WORK_CREATED', targetType: 'WORK_CASE', targetId: item.id } }); return item; }); return { id: row.id.toString() }; } catch { throw new ApiError(409, 'CONFLICT', '이미 사용 중인 작업사례 주소입니다.'); } }
export async function getWork(value: string) { const item = await db().workCase.findFirst({ where: { id: databaseId(value), deletedAt: null }, include: { workCaseImagesByWorkCaseId: { where: { deletedAt: null }, orderBy: [{ imageType: 'asc' }, { sortOrder: 'asc' }] } } }); if (!item) throw new ApiError(404, 'NOT_FOUND', '작업사례를 찾을 수 없습니다.'); return { id: item.id.toString(), title: item.title, slug: item.slug, category: item.category, location: item.location, buildingType: item.buildingType, workDate: item.workDate?.toISOString().slice(0,10), summary: item.summary, description: item.description, published: item.published, images: item.workCaseImagesByWorkCaseId.map(i => ({ id: i.id.toString(), imageType: i.imageType, altText: i.altText, sortOrder: i.sortOrder })) }; }
export async function updateWork(value: string, actor: string, input: Record<string, unknown>) { const id = databaseId(value); const current = await db().workCase.findFirst({ where: { id, deletedAt: null } }); if (!current) throw new ApiError(404, 'NOT_FOUND', '작업사례를 찾을 수 없습니다.'); try { await db().$transaction([db().workCase.update({ where: { id }, data: { ...input, ...(typeof input.workDate === 'string' ? { workDate: day(input.workDate) } : {}), ...(input.published === true && !current.published ? { publishedAt: new Date() } : {}), ...(input.published === false ? { publishedAt: null } : {}) } }), db().adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'WORK_UPDATED', targetType: 'WORK_CASE', targetId: id } })]); } catch { throw new ApiError(409, 'CONFLICT', '이미 사용 중인 작업사례 주소입니다.'); } return { updated: true }; }
export async function deleteWork(value: string, actor: string) { const id = databaseId(value); const item = await db().workCase.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new ApiError(404,'NOT_FOUND','작업사례를 찾을 수 없습니다.'); await db().$transaction([db().workCase.update({ where:{id},data:{deletedAt:new Date(),published:false,publishedAt:null}}),db().workCaseImage.updateMany({where:{workCaseId:id,deletedAt:null},data:{deletedAt:new Date()}}),db().adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'WORK_DELETED',targetType:'WORK_CASE',targetId:id}})]); return {deleted:true}; }
export async function listFaqs() { const rows=await db().faq.findMany({where:{deletedAt:null},orderBy:[{sortOrder:'asc'},{updatedAt:'desc'}]}); return rows.map(r=>({id:r.id.toString(),category:r.category,question:r.question,answer:r.answer,sortOrder:r.sortOrder,published:r.published})); }
export async function createFaq(actor:string,input:{category?:string;question:string;answer:string;sortOrder:number;published:boolean}) { const item=await db().$transaction(async tx=>{const row=await tx.faq.create({data:{...input,createdByAdminId:BigInt(actor)}});await tx.adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'FAQ_CREATED',targetType:'FAQ',targetId:row.id}});return row;});return {id:item.id.toString()}; }
export async function updateFaq(value:string,actor:string,input:Record<string,unknown>) { const id=databaseId(value); if(!await db().faq.findFirst({where:{id,deletedAt:null}})) throw new ApiError(404,'NOT_FOUND','FAQ를 찾을 수 없습니다.'); await db().$transaction([db().faq.update({where:{id},data:input}),db().adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'FAQ_UPDATED',targetType:'FAQ',targetId:id}})]);return {updated:true}; }
export async function deleteFaq(value:string,actor:string) { const id=databaseId(value); if(!await db().faq.findFirst({where:{id,deletedAt:null}})) throw new ApiError(404,'NOT_FOUND','FAQ를 찾을 수 없습니다.');await db().$transaction([db().faq.update({where:{id},data:{deletedAt:new Date(),published:false}}),db().adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'FAQ_DELETED',targetType:'FAQ',targetId:id}})]);return {deleted:true}; }
export async function listSettings() { return (await db().siteSetting.findMany({orderBy:{settingKey:'asc'}})).map(s=>({key:s.settingKey,value:s.settingValue,valueType:s.valueType,description:s.description})); }
export async function saveSettings(actor:string,items:{key:string;value:string|null;valueType:string;description?:string}[]) { await db().$transaction(async tx=>{for(const item of items) await tx.siteSetting.upsert({where:{settingKey:item.key},create:{settingKey:item.key,settingValue:item.value,valueType:item.valueType,description:item.description,updatedByAdminId:BigInt(actor)},update:{settingValue:item.value,valueType:item.valueType,description:item.description,updatedByAdminId:BigInt(actor)}});await tx.adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'SITE_SETTINGS_UPDATED'}});});return {updated:true}; }
export async function listUsers() { const rows=await db().admin.findMany({where:{deletedAt:null},orderBy:{createdAt:'asc'},select:{id:true,name:true,email:true,phone:true,role:true,status:true,lastLoginAt:true,createdAt:true}});return rows.map(r=>({...r,id:r.id.toString(),lastLoginAt:r.lastLoginAt?.toISOString()??null,createdAt:r.createdAt.toISOString()})); }
export async function createUser(actor:string,input:{name:string;email:string;phone?:string;role:'SUPER_ADMIN'|'MANAGER';password:string}) { const exists=await db().admin.findUnique({where:{email:input.email}});if(exists)throw new ApiError(409,'CONFLICT','이미 사용 중인 이메일입니다.');const row=await db().$transaction(async tx=>{const user=await tx.admin.create({data:{name:input.name,email:input.email,phone:input.phone,role:input.role,passwordHash:await hashPassword(input.password)}});await tx.adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'ADMIN_CREATED',targetType:'ADMIN',targetId:user.id}});return user;});return {id:row.id.toString()}; }
export async function updateUser(value:string,actor:string,input:Record<string,unknown>) { const id=databaseId(value);const user=await db().admin.findFirst({where:{id,deletedAt:null}});if(!user)throw new ApiError(404,'NOT_FOUND','관리자를 찾을 수 없습니다.');if(id===BigInt(actor)&&input.status&&input.status!=='ACTIVE')throw new ApiError(422,'VALIDATION_ERROR','현재 로그인한 계정은 비활성화할 수 없습니다.');await db().$transaction([db().admin.update({where:{id},data:input}),db().adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'ADMIN_UPDATED',targetType:'ADMIN',targetId:id}})]);return {updated:true}; }
export async function resetPassword(value:string,actor:string,password:string) { const id=databaseId(value);if(!await db().admin.findFirst({where:{id,deletedAt:null}}))throw new ApiError(404,'NOT_FOUND','관리자를 찾을 수 없습니다.');await db().$transaction([db().admin.update({where:{id},data:{passwordHash:await hashPassword(password)}}),db().adminSession.deleteMany({where:{adminId:id}}),db().adminActivityLog.create({data:{adminId:BigInt(actor),actionType:'ADMIN_PASSWORD_RESET',targetType:'ADMIN',targetId:id}})]);return {updated:true}; }
