import 'server-only';
import type { EstimateStatus, Prisma, VisitStatus } from '@/generated/prisma/client';
import { db } from '@/lib/db';
import { ApiError } from '@/lib/http';
import { databaseId } from '@/services/attachments';

const clock = (value?: string) => value ? new Date(`1970-01-01T${value}:00.000Z`) : null;
async function activeAdmin(tx: Prisma.TransactionClient, id: bigint | null | undefined) { if (id && !await tx.admin.findFirst({ where: { id, status: 'ACTIVE', deletedAt: null } })) throw new ApiError(422, 'VALIDATION_ERROR', '활성 관리자를 선택해주세요.'); }
async function updateInquiryStatus(tx: Prisma.TransactionClient, inquiryId: bigint, next: 'VISIT_SCHEDULED' | 'VISIT_COMPLETED', actorId: bigint) {
  const inquiry = await tx.inquiry.findUniqueOrThrow({ where: { id: inquiryId }, select: { status: true } }); if (inquiry.status === next) return;
  await tx.inquiry.update({ where: { id: inquiryId }, data: { status: next } });
  await tx.inquiryStatusHistory.create({ data: { inquiryId, previousStatus: inquiry.status, newStatus: next, changedByAdminId: actorId, memo: next === 'VISIT_COMPLETED' ? '방문 완료 처리' : '방문 일정 등록' } });
}
export async function createVisit(value: string, actor: string, input: { visitDate: string; visitTime?: string; assignedAdminId?: string | null; address: string; addressDetail?: string; memo?: string; changeInquiryStatus: boolean }) {
  const inquiryId = databaseId(value); return db().$transaction(async tx => { const inquiry = await tx.inquiry.findFirst({ where: { id: inquiryId, deletedAt: null } }); if (!inquiry) throw new ApiError(404, 'NOT_FOUND', '접수를 찾을 수 없습니다.'); const assignedAdminId = input.assignedAdminId ? BigInt(input.assignedAdminId) : null; await activeAdmin(tx, assignedAdminId); const visit = await tx.visit.create({ data: { inquiryId, assignedAdminId, visitDate: new Date(`${input.visitDate}T00:00:00+09:00`), visitTime: clock(input.visitTime), address: input.address, addressDetail: input.addressDetail, memo: input.memo, createdByAdminId: BigInt(actor) } }); if (input.changeInquiryStatus) await updateInquiryStatus(tx, inquiryId, 'VISIT_SCHEDULED', BigInt(actor)); await tx.adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'VISIT_CREATED', targetType: 'VISIT', targetId: visit.id } }); return { id: visit.id.toString() }; });
}
export async function updateVisit(value: string, actor: string, input: { visitDate?: string; visitTime?: string; assignedAdminId?: string | null; address?: string; addressDetail?: string; memo?: string }) { const visitId = databaseId(value); return db().$transaction(async tx => { const visit = await tx.visit.findFirst({ where: { id: visitId, deletedAt: null, inquiry: { deletedAt: null } } }); if (!visit) throw new ApiError(404, 'NOT_FOUND', '방문 일정을 찾을 수 없습니다.'); const assignedAdminId = input.assignedAdminId === undefined ? undefined : input.assignedAdminId ? BigInt(input.assignedAdminId) : null; await activeAdmin(tx, assignedAdminId); await tx.visit.update({ where: { id: visitId }, data: { ...(input.visitDate ? { visitDate: new Date(`${input.visitDate}T00:00:00+09:00`) } : {}), ...(input.visitTime !== undefined ? { visitTime: clock(input.visitTime) } : {}), ...(assignedAdminId !== undefined ? { assignedAdminId } : {}), ...(input.address ? { address: input.address } : {}), ...(input.addressDetail !== undefined ? { addressDetail: input.addressDetail } : {}), ...(input.memo !== undefined ? { memo: input.memo } : {}) } }); await tx.adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'VISIT_UPDATED', targetType: 'VISIT', targetId: visitId } }); return { updated: true }; }); }
export async function changeVisitStatus(value: string, actor: string, status: VisitStatus, change: boolean) { const visitId = databaseId(value); return db().$transaction(async tx => { const visit = await tx.visit.findFirst({ where: { id: visitId, deletedAt: null, inquiry: { deletedAt: null } } }); if (!visit) throw new ApiError(404, 'NOT_FOUND', '방문 일정을 찾을 수 없습니다.'); await tx.visit.update({ where: { id: visitId }, data: { status } }); if (change && status !== 'CANCELED') await updateInquiryStatus(tx, visit.inquiryId, status === 'COMPLETED' ? 'VISIT_COMPLETED' : 'VISIT_SCHEDULED', BigInt(actor)); await tx.adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'VISIT_STATUS_CHANGED', targetType: 'VISIT', targetId: visitId } }); return { status }; }); }
export async function listVisits(query: { from?: string; to?: string; status?: VisitStatus; assignedAdminId?: string }) { const visits = await db().visit.findMany({ where: { deletedAt: null, inquiry: { deletedAt: null }, ...(query.status ? { status: query.status } : {}), ...(query.assignedAdminId ? { assignedAdminId: BigInt(query.assignedAdminId) } : {}), ...((query.from || query.to) ? { visitDate: { ...(query.from ? { gte: new Date(`${query.from}T00:00:00+09:00`) } : {}), ...(query.to ? { lte: new Date(`${query.to}T23:59:59+09:00`) } : {}) } } : {}) }, orderBy: [{ visitDate: 'asc' }, { visitTime: 'asc' }], include: { inquiry: { select: { id: true, inquiryNumber: true, customerName: true, phone: true } }, assignedAdmin: { select: { id: true, name: true } } } }); return { items: visits.map(v => ({ id: v.id.toString(), visitDate: v.visitDate.toISOString().slice(0, 10), visitTime: v.visitTime?.toISOString() ?? null, status: v.status, address: v.address, addressDetail: v.addressDetail, memo: v.memo, inquiry: { id: v.inquiry.id.toString(), inquiryNumber: v.inquiry.inquiryNumber, customerName: v.inquiry.customerName, phone: v.inquiry.phone }, assignedAdmin: v.assignedAdmin && { id: v.assignedAdmin.id.toString(), name: v.assignedAdmin.name } })) }; }
export async function createEstimate(value: string, actor: string, input: { amount?: number | string; memo?: string; status: EstimateStatus }) { const inquiryId = databaseId(value); return db().$transaction(async tx => { if (!await tx.inquiry.findFirst({ where: { id: inquiryId, deletedAt: null } })) throw new ApiError(404, 'NOT_FOUND', '접수를 찾을 수 없습니다.'); const estimate = await tx.estimate.create({ data: { inquiryId, amount: input.amount?.toString(), memo: input.memo, status: input.status, createdByAdminId: BigInt(actor) } }); await tx.adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'ESTIMATE_CREATED', targetType: 'ESTIMATE', targetId: estimate.id } }); return { id: estimate.id.toString() }; }); }
export async function updateEstimate(value: string, actor: string, input: { amount?: number | string; memo?: string; status?: EstimateStatus }) { const estimateId = databaseId(value); const estimate = await db().estimate.findFirst({ where: { id: estimateId, deletedAt: null, inquiry: { deletedAt: null } } }); if (!estimate) throw new ApiError(404, 'NOT_FOUND', '견적을 찾을 수 없습니다.'); await db().$transaction([db().estimate.update({ where: { id: estimateId }, data: { ...(input.amount !== undefined ? { amount: input.amount.toString() } : {}), ...(input.memo !== undefined ? { memo: input.memo } : {}), ...(input.status ? { status: input.status } : {}) } }), db().adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'ESTIMATE_UPDATED', targetType: 'ESTIMATE', targetId: estimateId } })]); return { updated: true }; }
export async function deleteEstimate(value: string, actor: string) { const estimateId = databaseId(value); const estimate = await db().estimate.findFirst({ where: { id: estimateId, deletedAt: null, inquiry: { deletedAt: null } } }); if (!estimate) throw new ApiError(404, 'NOT_FOUND', '견적을 찾을 수 없습니다.'); await db().$transaction([db().estimate.update({ where: { id: estimateId }, data: { deletedAt: new Date() } }), db().inquiryAttachment.updateMany({ where: { estimateId }, data: { estimateId: null } }), db().adminActivityLog.create({ data: { adminId: BigInt(actor), actionType: 'ESTIMATE_DELETED', targetType: 'ESTIMATE', targetId: estimateId } })]); return { deleted: true }; }
