'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

type Admin = { id: string; name: string };
type Visit = { id: string; visitDate: string; visitTime: string | null; address: string; addressDetail: string | null; memo: string | null; status: string; assignedAdmin: Admin | null };
type Estimate = { id: string; amount: string | null; memo: string | null; status: string; createdAt: string };
type Attachment = { id: string; originalName: string; attachmentType: string; estimateId?: string | null };
async function call(url: string, method: string, body?: object) { const response = await fetch(url, { method, credentials: 'same-origin', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined }); const json = await response.json().catch(() => null) as { data?: unknown; error?: { message?: string } } | null; if (!response.ok) throw new Error(json?.error?.message ?? '요청을 처리하지 못했습니다.'); return json?.data as { url?: string; headers?: Record<string, string>; uploadId?: string }; }
function timeLabel(value: string | null) { return value ? value.slice(11, 16) : '시간 미정'; }
export function VisitEstimateOperations({ inquiryId, admins, visits, estimates, attachments, address, addressDetail }: { inquiryId: string; admins: Admin[]; visits: Visit[]; estimates: Estimate[]; attachments: Attachment[]; address: string; addressDetail: string | null }) {
  const router = useRouter(); const [notice, setNotice] = useState<string>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const [date, setDate] = useState(''); const [time, setTime] = useState(''); const [assignee, setAssignee] = useState(''); const [memo, setMemo] = useState(''); const [amount, setAmount] = useState(''); const [estimateMemo, setEstimateMemo] = useState(''); const [fileType, setFileType] = useState('BEFORE'); const [estimateId, setEstimateId] = useState('');
  const run = async (task: () => Promise<void>, message: string) => { setBusy(true); setError(undefined); setNotice(undefined); try { await task(); setNotice(message); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : '요청을 처리하지 못했습니다.'); } finally { setBusy(false); } };
  const upload = async (file: File) => { const digest = await crypto.subtle.digest('SHA-256', await file.arrayBuffer()); const sha256 = Array.from(new Uint8Array(digest), b => b.toString(16).padStart(2, '0')).join(''); const base = `/api/admin/inquiries/${inquiryId}/attachments`; const reserved = await call(base, 'POST', { clientId: crypto.randomUUID(), originalName: file.name, mimeType: file.type, fileSize: file.size, sha256, attachmentType: fileType, estimateId: fileType === 'ESTIMATE' && estimateId ? estimateId : undefined }); if (!reserved.url || !reserved.headers || !reserved.uploadId) throw new Error('파일 업로드 준비에 실패했습니다.'); const put = await fetch(reserved.url, { method: 'PUT', headers: reserved.headers, body: file, credentials: 'omit' }); if (!put.ok) throw new Error('파일 전송에 실패했습니다.'); await call(`${base}/${reserved.uploadId}/complete`, 'POST'); };
  return <section id="visit-estimate" className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-bold">방문 · 견적 · 현장 사진</h2>{notice && <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><form onSubmit={e => { e.preventDefault(); void run(async () => { await call(`/api/admin/inquiries/${inquiryId}/visits`, 'POST', { visitDate: date, visitTime: time || undefined, assignedAdminId: assignee || null, address, addressDetail: addressDetail || undefined, memo: memo || undefined, changeInquiryStatus: true }); setDate(''); setTime(''); setMemo(''); }, '방문 일정을 등록했습니다.'); }} className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">방문 일정 등록</h3><label className="mt-3 block text-sm font-semibold">날짜<input required type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"/></label><label className="mt-3 block text-sm font-semibold">시간 <input type="time" value={time} onChange={e => setTime(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"/></label><label className="mt-3 block text-sm font-semibold">담당자<select value={assignee} onChange={e => setAssignee(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="">미배정</option>{admins.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="mt-3 block text-sm font-semibold">메모<textarea value={memo} onChange={e => setMemo(e.target.value)} maxLength={5000} className="mt-1 min-h-20 w-full rounded-lg border border-slate-300 bg-white p-3 text-sm"/></label><button disabled={busy} className="mt-3 min-h-11 w-full rounded-lg bg-slate-900 px-4 text-sm font-bold text-white disabled:opacity-50">일정 등록</button></form>
      <form onSubmit={e => { e.preventDefault(); void run(async () => { await call(`/api/admin/inquiries/${inquiryId}/estimates`, 'POST', { amount: amount || undefined, memo: estimateMemo || undefined, status: 'DRAFT' }); setAmount(''); setEstimateMemo(''); }, '견적을 등록했습니다.'); }} className="rounded-xl bg-slate-50 p-4"><h3 className="font-bold">견적 등록</h3><label className="mt-3 block text-sm font-semibold">금액 <input inputMode="numeric" value={amount} onChange={e => setAmount(e.target.value)} placeholder="예: 500000" className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3"/></label><label className="mt-3 block text-sm font-semibold">견적 메모<textarea value={estimateMemo} onChange={e => setEstimateMemo(e.target.value)} maxLength={5000} className="mt-1 min-h-28 w-full rounded-lg border border-slate-300 bg-white p-3 text-sm"/></label><button disabled={busy} className="mt-3 min-h-11 w-full rounded-lg bg-red-700 px-4 text-sm font-bold text-white disabled:opacity-50">견적 등록</button></form></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="font-bold">등록된 방문</h3><ul className="mt-3 space-y-2">{visits.length ? visits.map(v => <li key={v.id} className="rounded-xl border border-slate-200 p-3 text-sm"><strong>{v.visitDate} {timeLabel(v.visitTime)}</strong><p className="mt-1 text-slate-600">{v.assignedAdmin?.name ?? '미배정'} · {v.status === 'COMPLETED' ? '방문 완료' : v.status === 'CANCELED' ? '취소' : '예정'}</p>{v.status === 'SCHEDULED' && <button disabled={busy} onClick={() => void run(() => call(`/api/admin/visits/${v.id}/status`, 'PATCH', { status: 'COMPLETED', changeInquiryStatus: true }).then(() => undefined), '방문 완료로 처리했습니다.')} className="mt-2 min-h-10 rounded-lg border border-slate-300 px-3 text-xs font-bold">방문 완료</button>}</li>) : <li className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">등록된 일정이 없습니다.</li>}</ul></div><div><h3 className="font-bold">등록된 견적</h3><ul className="mt-3 space-y-2">{estimates.length ? estimates.map(e => <li key={e.id} className="rounded-xl border border-slate-200 p-3 text-sm"><strong>{e.amount ? `${Number(e.amount).toLocaleString('ko-KR')}원` : '금액 미정'}</strong><p className="mt-1 text-slate-600">{e.status} {e.memo && `· ${e.memo}`}</p><button disabled={busy} onClick={() => void run(() => call(`/api/admin/estimates/${e.id}`, 'DELETE').then(() => undefined), '견적을 삭제했습니다.')} className="mt-2 text-xs font-bold text-red-700">삭제</button></li>) : <li className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500">등록된 견적이 없습니다.</li>}</ul></div></div>
    <form onSubmit={e => { e.preventDefault(); const file = new FormData(e.currentTarget).get('file'); if (file instanceof File && file.size) void run(() => upload(file), '현장 파일을 등록했습니다.'); }} className="mt-6 border-t border-slate-200 pt-5"><h3 className="font-bold">현장 사진 · 견적 파일</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><select value={fileType} onChange={e => setFileType(e.target.value)} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="BEFORE">작업 전 사진</option><option value="WORKING">작업 중 사진</option><option value="AFTER">작업 완료 사진</option><option value="ESTIMATE">견적 파일</option><option value="ETC">기타 사진</option></select>{fileType === 'ESTIMATE' && <select value={estimateId} onChange={e => setEstimateId(e.target.value)} className="min-h-11 rounded-lg border border-slate-300 px-3"><option value="">견적 연결 안 함</option>{estimates.map(e => <option key={e.id} value={e.id}>{e.amount ? `${Number(e.amount).toLocaleString()}원` : '금액 미정'} 견적</option>)}</select>}<input required name="file" type="file" accept={fileType === 'ESTIMATE' ? '.pdf,.jpg,.jpeg,.png,.xlsx' : '.jpg,.jpeg,.png,.webp,.heic,.heif'} className="min-h-11 text-sm"/></div><button disabled={busy} className="mt-3 min-h-11 rounded-lg border border-slate-300 px-4 text-sm font-bold">파일 올리기</button></form>
    <ul className="mt-4 grid gap-2 sm:grid-cols-2">{attachments.filter(a => a.attachmentType !== 'CUSTOMER').map(a => <li key={a.id} className="flex items-center justify-between gap-2 rounded-lg bg-slate-50 p-3 text-sm"><button type="button" onClick={() => void run(async () => { const file = await call(`/api/admin/attachments/${a.id}/url`, 'GET'); if (!file.url) throw new Error('파일 주소를 가져오지 못했습니다.'); window.open(file.url, '_blank', 'noopener,noreferrer'); }, '파일을 열었습니다.')} className="truncate text-left font-semibold underline">{a.originalName}</button><button disabled={busy} onClick={() => void run(() => call(`/api/admin/attachments/${a.id}`, 'DELETE').then(() => undefined), '첨부 파일을 삭제했습니다.')} className="shrink-0 text-xs font-bold text-red-700">삭제</button></li>)}</ul>
  </section>;
}
