import Link from 'next/link';

export type Service = { slug: string; title: string; text: string; number: string; overview: string; steps: string[]; checks: string[]; faq: { question: string; answer: string } };

export const services: Service[] = [
  { slug: 'fire-electric', title: '소방전기', text: '감지기·수신기·유도등 등 소방전기 설비를 현장에 맞게 점검하고 시공합니다.', number: '01', overview: '소방전기는 화재 신호를 감지하고 경보·피난 설비가 제때 작동하도록 연결하는 기반입니다. 설비 구성과 배선 상태, 신호 이상 여부를 현장에서 확인해 필요한 조치를 안내합니다.', steps: ['감지기·수신기·유도등 등 현장 설비 확인', '배선·전원·신호 상태와 이상 구간 점검', '보수 또는 시공 범위와 일정 안내'], checks: ['감지기와 수신기의 신호 상태', '유도등·비상전원·표시 설비의 작동 상태', '증설·용도 변경에 따른 설비 검토'], faq: { question: '소방전기 이상 신호가 반복되면 무엇을 확인하나요?', answer: '수신기 표시, 감지기 상태, 배선과 전원 상태를 현장에서 확인한 뒤 원인과 필요한 조치를 안내합니다.' } },
  { slug: 'fire-construction', title: '소방공사업체 · 소방설비 시공', text: '건물 용도와 현장 조건을 확인해 필요한 소방설비 시공 범위를 안내합니다.', number: '02', overview: '소방설비 시공은 건물의 용도와 규모, 기존 설비 상태를 함께 봐야 합니다. 현장 확인을 바탕으로 필요한 설비 구성과 공사 범위를 정리하고 진행 순서를 안내합니다.', steps: ['건물 용도·공사 범위·기존 설비 확인', '필요한 소방설비 구성과 시공 범위 안내', '일정·현장 여건을 반영한 진행 계획 공유'], checks: ['신축·증축·용도 변경에 필요한 설비', '기존 설비의 보수 또는 교체 필요 구간', '공사 중 이용자와 현장 안전을 고려한 일정'], faq: { question: '소방공사는 상담 전에 무엇을 준비하면 좋나요?', answer: '건물 용도, 현재 설비 사진, 공사 예정 범위와 희망 일정이 있으면 현장 확인과 상담에 도움이 됩니다.' } },
  { slug: 'fire-inspection', title: '소방점검', text: '정기 점검부터 설비 이상 확인까지, 필요한 조치를 이해하기 쉽게 안내합니다.', number: '03', overview: '소방점검은 설비가 실제 상황에서 제 역할을 할 수 있는지 확인하는 과정입니다. 현장의 설비 상태와 관리 이력을 확인하고, 필요한 보수·교체 항목을 이해하기 쉽게 설명합니다.', steps: ['점검 대상 설비와 관리 이력 확인', '설비 상태·작동 이상 여부 점검', '조치가 필요한 항목과 우선순위 안내'], checks: ['경보·피난·소화 설비의 상태', '수신기 표시와 감지기 이상 신호', '관리 중 확인된 불편 사항과 보수 필요 항목'], faq: { question: '소방점검에서 이상이 발견되면 바로 공사해야 하나요?', answer: '현장 상태와 조치 필요성을 먼저 설명드리고, 필요한 경우 보수·교체 범위와 일정을 별도로 안내합니다.' } },
  { slug: 'sprinkler-installation', title: '스프링클러 설치', text: '건물 용도와 공간 구성을 확인해 스프링클러 설치·보수 범위를 안내합니다.', number: '04', overview: '스프링클러 설비는 화재 초기 대응을 위해 공간별 조건을 고려해 설치·관리해야 합니다. 천장 구조와 용도, 기존 배관과 헤드 상태를 확인한 뒤 필요한 범위를 제안합니다.', steps: ['공간 용도·천장 구조·기존 설비 확인', '헤드·배관 상태와 설치 또는 보수 범위 검토', '공사 전 현장 여건과 일정 안내'], checks: ['누수·부식 등 배관과 헤드 상태', '공간 변경에 따른 헤드 배치 검토', '기존 설비와 추가 설치 구간의 연결 조건'], faq: { question: '인테리어 공사 중 스프링클러 위치를 바꿔도 되나요?', answer: '공간 변경 내용과 기존 설비를 함께 확인해야 합니다. 공사 전에 현장 조건을 알려주시면 필요한 검토 항목을 안내합니다.' } },
  { slug: 'fire-alarm-detection', title: '화재경보기 · 자동화재탐지설비', text: '화재경보기와 자동화재탐지설비의 이상 신호, 교체·보수 필요 사항을 확인합니다.', number: '05', overview: '화재경보기와 자동화재탐지설비는 화재 신호를 빠르게 알리는 설비입니다. 경보 오작동, 수신기 이상 표시, 감지기 교체 필요 여부를 현장 설비 상태에 따라 확인합니다.', steps: ['수신기 표시와 경보 발생 상황 확인', '감지기·발신기·경종 등 관련 설비 점검', '원인 설명과 보수·교체 필요 항목 안내'], checks: ['반복되는 경보 또는 이상 표시', '감지기 오염·노후와 교체 필요 여부', '수신기·경종·발신기의 연결과 작동 상태'], faq: { question: '화재경보기가 울렸는데 화재가 아니면 어떻게 하나요?', answer: '임의로 설비를 해제하기보다 수신기 표시와 현장 상황을 확인해야 합니다. 반복되는 경우 원인 점검을 요청해주세요.' } },
  { slug: 'seoul-fire-services', title: '서울 소방업체 상담', text: '서울 지역의 소방전기, 소방설비, 소방점검과 화재경보기 관련 현장 상담을 받습니다.', number: '06', overview: '서울 지역 현장은 상가·사무실·공장·공동주택 등 건물 용도와 운영 환경이 다양합니다. OK소방은 현장 상황을 먼저 듣고 소방전기, 설비 시공, 점검 중 필요한 상담 범위를 안내합니다.', steps: ['서울 현장 주소와 건물 용도 확인', '현재 설비와 문의 상황을 바탕으로 상담 범위 정리', '방문 또는 후속 안내가 필요한 항목과 일정 조율'], checks: ['서울 지역 현장 위치와 출입·운영 조건', '소방점검·설비 시공·경보기 이상 등 문의 유형', '사진, 기존 점검 내용, 희망 일정 등 제공 정보'], faq: { question: '서울 외 지역도 상담할 수 있나요?', answer: '우선 현장 위치와 문의 내용을 남겨주시면 대응 가능 여부와 상담 방법을 안내합니다.' } },
];

export function ServiceCards({ compact = false }: { compact?: boolean }) {
  return <div className={`grid gap-4 ${compact ? 'md:grid-cols-3' : 'md:grid-cols-2 xl:grid-cols-3'}`}>{services.map(service => <article key={service.slug} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-red-200 hover:shadow-md"><p className="text-sm font-black text-red-700">{service.number}</p><h3 className="mt-8 text-xl font-black">{service.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{service.text}</p><Link href={`/services/${service.slug}`} className="mt-6 inline-flex min-h-11 items-center font-bold text-red-700">자세히 보기 →</Link></article>)}</div>;
}
