import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { PublicShell } from '@/components/public/public-site';
import { services } from '@/components/public/service-cards';
import { TrackView } from '@/components/public/analytics';
export function generateStaticParams() { return services.map(service => ({ slug: service.slug })); }
export async function generateMetadata({ params }: PageProps<'/services/[slug]'>): Promise<Metadata> { const slug = (await params).slug; const service = services.find(item => item.slug === slug); return service ? { title: service.title, description: service.text, alternates: { canonical: `/services/${slug}` }, openGraph: { title: `${service.title} | OK소방`, description: service.text } } : {}; }
const details: Record<string, string[]> = { 'fire-electric': ['감지기·수신기·유도등 등 설비 상태 확인', '현장 조건에 맞춘 소방 전기 설비 시공', '이상 신호와 교체·보수 필요 사항 안내'], 'fire-construction': ['건물 용도와 현장 조건 확인', '필요한 설비 구성과 시공 범위 안내', '공사 일정과 진행 과정 공유'], 'fire-inspection': ['소방시설의 현재 상태 확인', '점검 결과와 필요한 조치 설명', '정기 관리가 필요한 항목 안내'] };
export default async function ServiceDetail({ params }: PageProps<'/services/[slug]'>) { const slug = (await params).slug; const service = services.find(item => item.slug === slug); if (!service) notFound(); return <PublicShell><main><TrackView event="service_view" value={service.slug}/><section className="bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-5 py-20 lg:px-8"><p className="text-sm font-bold tracking-widest text-red-400">SERVICE {service.number}</p><h1 className="mt-5 text-4xl font-black sm:text-6xl">{service.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{service.text}</p></div></section><section className="mx-auto max-w-5xl px-5 py-20 lg:px-8"><h2 className="text-3xl font-black">이렇게 진행합니다</h2><ul className="mt-8 grid gap-4">{details[service.slug].map((item, i) => <li key={item} className="flex gap-5 rounded-2xl border border-slate-200 p-6"><span className="font-black text-red-700">0{i + 1}</span><p className="font-bold">{item}</p></li>)}</ul><Link href="/contact" className="mt-10 inline-flex min-h-14 items-center rounded-xl bg-red-700 px-6 font-bold text-white">상담 접수하기 →</Link></section></main></PublicShell>; }
