import Link from 'next/link';
import { PublicShell } from '@/components/public/public-site';
import { ServiceCards } from '@/components/public/service-cards';
import { GuideCards } from '@/components/public/guide-cards';
import { PhoneConsultationLink } from '@/components/public/phone-consultation-link';
import { JsonLd } from '@/components/public/json-ld';
import { siteUrl } from '@/lib/site-url';
export default function Home() {
  const website = { '@context': 'https://schema.org', '@type': 'WebSite', '@id': `${siteUrl()}/#website`, name: 'OK소방', alternateName: 'okfire.kr', url: siteUrl(), publisher: { '@id': `${siteUrl()}/#business` } };
  return <PublicShell><JsonLd data={website}/><main><section className="overflow-hidden bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:py-28 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:py-36"><div><p className="inline-flex items-center rounded-full border border-red-400/40 bg-red-500/15 px-4 py-2 text-sm font-black tracking-[0.18em] text-red-300">30년 현장 경험</p><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-6xl lg:text-7xl"><span className="block text-red-400">30년 현장 경험으로,</span>소방설비는<br/>경험이 중요합니다.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-300">소방전기 · 소방설비 시공 · 설비 보수 전문.<br/>현장 상황을 이해하는 OK소방이 함께합니다.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><PhoneConsultationLink variant="hero"/><Link href="/contact" className="inline-flex min-h-14 items-center justify-center rounded-xl bg-red-700 px-7 font-bold text-white hover:bg-red-600">간편 상담 접수 →</Link></div></div><div className="relative min-h-72 rounded-3xl border border-red-400/30 bg-[radial-gradient(circle_at_70%_25%,#ef4444_0,transparent_25%),linear-gradient(145deg,#25344a,#0f172a_65%)] p-7"><p className="text-sm font-bold text-slate-300">현장 중심 소방 서비스</p><div className="absolute bottom-7 left-7 right-7 rounded-2xl border border-red-300/30 bg-red-500/15 p-5 backdrop-blur"><p className="text-5xl font-black leading-none">30<span className="text-red-400">+</span></p><p className="mt-2 text-lg font-bold text-white">년 현장 경험</p><p className="mt-2 text-sm text-slate-300">필요한 내용을 먼저 확인하고<br/>현장에 맞게 안내합니다.</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-18 sm:py-24 lg:px-8"><p className="text-sm font-bold tracking-widest text-red-700">OK FIRE SAFETY</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">현장을 이해하고, 필요한 일을 정확히 안내합니다.</h2><div className="mt-10 grid gap-4 sm:grid-cols-3">{[['30년','현장 경험'],['3가지','핵심 전문 분야'],['모바일','간편 상담 접수']].map(([strong, label]) => <div key={strong} className="rounded-2xl bg-slate-100 p-6"><strong className="text-3xl font-black text-red-700">{strong}</strong><p className="mt-3 text-sm font-bold text-slate-700">{label}</p></div>)}</div></section>
    <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-18 sm:py-24 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-widest text-red-700">SERVICES</p><h2 className="mt-3 text-3xl font-black">주요 서비스</h2></div><Link href="/services" className="min-h-11 pt-2 text-sm font-bold text-red-700">전체 서비스 보기 →</Link></div><div className="mt-8"><ServiceCards compact/></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-18 sm:py-24 lg:px-8"><p className="text-sm font-bold tracking-widest text-red-700">WHEN TO CONTACT</p><h2 className="mt-3 text-3xl font-black">이런 경우 문의하세요</h2><div className="mt-8 grid gap-3 lg:grid-cols-3">{['노후된 소방설비를 교체하거나 보수하고 싶어요.','감지기나 유도등이 자주 이상을 알려요.','건물 공사에 맞춰 소방설비를 새로 설치해야 해요.'].map((question, i) => <div key={question} className="rounded-2xl border border-slate-200 p-6"><p className="text-sm font-black text-red-700">0{i + 1}</p><p className="mt-8 text-lg font-bold leading-7">{question}</p></div>)}</div></section>
    <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-18 sm:py-24 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold tracking-widest text-red-700">FIRE SAFETY GUIDE</p><h2 className="mt-3 text-3xl font-black">알아두면 좋은 소방설비 이야기</h2></div><Link href="/guides" className="inline-flex min-h-11 items-center text-sm font-bold text-red-700">전체 가이드 보기 →</Link></div><div className="mt-8"><GuideCards limit={4}/></div></div></section>
    <section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-18 sm:py-24 lg:px-8"><p className="text-sm font-bold tracking-widest text-red-400">PROCESS</p><h2 className="mt-3 text-3xl font-black">상담부터 현장 확인까지</h2><ol className="mt-10 grid gap-5 md:grid-cols-4">{['간편 상담 접수','내용 확인 및 연락','현장 방문 일정 조율','보수 · 시공 · 견적 안내'].map((step, i) => <li key={step} className="border-t border-white/20 pt-4"><span className="text-sm font-black text-red-400">0{i + 1}</span><p className="mt-4 font-bold leading-6">{step}</p></li>)}</ol></div></section>
    <section className="mx-auto max-w-7xl px-5 py-18 sm:py-24 lg:px-8"><div className="rounded-3xl bg-red-700 px-7 py-12 text-white sm:px-12"><p className="text-sm font-bold tracking-widest text-red-100">CONSULTATION</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">현장 상황을 알려주세요.</h2><p className="mt-4 text-sm leading-7 text-red-50">확인 후 상담을 도와드리겠습니다.</p><Link href="/contact" className="mt-8 inline-flex min-h-14 items-center rounded-xl bg-white px-6 font-bold text-red-800">간편 상담 접수 →</Link></div></section></main></PublicShell>;
}
