import assert from 'node:assert/strict';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import sharp from 'sharp';
import type { APIRequestContext } from '@playwright/test';
import type { Pool } from 'pg';
export async function testUploads(api: APIRequestContext, pool: Pool, origin: string, login: () => Promise<unknown>) {
  const makeInquiry = async () => {
    const key = randomUUID();
    const response = await api.post('/api/inquiries', { headers: { origin, 'Idempotency-Key': key }, data: { inquiryType: 'REPAIR', customerName: '사진 테스트', phone: '01011112222', address: '테스트 현장', description: '사진 업로드 테스트', privacyAgreed: true, privacyPolicyVersion: 'integration-test-only' } });
    assert.equal(response.status(), 201);
    return { id: (await response.json()).data.id as string, key };
  };
  const owner = await makeInquiry();
  const png = await sharp({ create: { width: 40, height: 30, channels: 3, background: '#aa1100' } }).withMetadata().png().toBuffer();
  const payload = (bytes = png, name = '현장.png', mime = 'image/png') => ({ clientId: randomUUID(), originalName: name, mimeType: mime, fileSize: bytes.length, sha256: createHash('sha256').update(bytes).digest('hex') });
  const headers = { origin, 'X-Inquiry-Key': owner.key };
  const base = `/api/inquiries/${owner.id}/attachments`;
  const reserve = (data = payload(), path = base, key = owner.key) => api.post(path, { headers: { origin, 'X-Inquiry-Key': key }, data });
  const finalize = (uploadId: string, path = base) => api.post(`${path}/${uploadId}/complete`, { headers });
  assert.equal((await api.post(base, { headers: { origin }, data: payload() })).status(), 401);
  assert.equal((await reserve(payload(), base, randomUUID())).status(), 403);
  assert.equal((await api.post(base, { headers: { ...headers, origin: 'https://evil.example' }, data: payload() })).status(), 403);
  assert.equal((await reserve({ ...payload(), fileSize: 10 * 1024 * 1024 + 1 })).status(), 413);
  assert.equal((await reserve({ ...payload(), originalName: 'bad.svg' })).status(), 422);
  assert.equal((await reserve({ ...payload(), originalName: '../bad.png' })).status(), 422);
  const original = payload();
  const reserved = await reserve(original); assert.equal(reserved.status(), 201, await reserved.text());
  const ticket = (await reserved.json()).data;
  const signed = new URL(ticket.url);
  assert.ok(signed.searchParams.has('X-Amz-Signature')); assert.equal(signed.searchParams.get('X-Amz-Expires'), '300');
  assert.ok(signed.searchParams.get('X-Amz-SignedHeaders')!.includes('content-length'));
  assert.equal((await reserve(original)).status(), 201);
  assert.equal((await reserve({ ...original, sha256: '0'.repeat(64) })).status(), 409);
  assert.equal((await finalize(ticket.uploadId)).status(), 400);
  const put = await api.put(ticket.url, { headers: ticket.headers, data: png }); assert.ok(put.ok(), await put.text());
  const completed = await finalize(ticket.uploadId); assert.equal(completed.status(), 200, await completed.text());
  const attachmentId = (await completed.json()).data.id;
  assert.equal((await finalize(ticket.uploadId)).status(), 200);
  assert.equal((await (await reserve(original)).json()).data.complete, true);
  assert.equal((await pool.query('SELECT count(*) FROM inquiry_attachments WHERE inquiry_id=$1', [owner.id])).rows[0].count, '1');
  const row = (await pool.query('SELECT * FROM inquiry_attachments WHERE id=$1', [attachmentId])).rows[0];
  assert.equal(row.mime_type, 'image/jpeg'); assert.ok(row.storage_key.startsWith('private/')); assert.ok(!row.storage_key.includes('현장'));
  assert.equal(row.uploader_type, 'CUSTOMER');
  assert.equal((await api.get(`/api/admin/attachments/${attachmentId}/url`)).status(), 401);
  await login();
  const download = await api.get(`/api/admin/attachments/${attachmentId}/url`); assert.equal(download.status(), 200);
  const downloadData = (await download.json()).data; assert.equal(downloadData.expiresIn, 60);
  const downloaded = await api.get(downloadData.url); assert.equal(downloaded.status(), 200);
  const image = await sharp(await downloaded.body()).metadata(); assert.equal(image.format, 'jpeg'); assert.equal(image.exif, undefined);
  // Reusing the original PUT URL cannot overwrite the separately stored final image.
  await api.put(ticket.url, { headers: ticket.headers, data: png });
  assert.deepEqual(await (await api.get(downloadData.url)).body(), await downloaded.body());
  await pool.query('UPDATE inquiry_attachments SET deleted_at=now() WHERE id=$1', [attachmentId]);
  assert.equal((await api.get(`/api/admin/attachments/${attachmentId}/url`)).status(), 404);
  await pool.query('UPDATE inquiry_attachments SET deleted_at=NULL WHERE id=$1', [attachmentId]);
  await pool.query('UPDATE inquiries SET deleted_at=now() WHERE id=$1', [owner.id]);
  assert.equal((await api.get(`/api/admin/attachments/${attachmentId}/url`)).status(), 404);
  assert.equal((await reserve()).status(), 403);
  await pool.query('UPDATE inquiries SET deleted_at=NULL WHERE id=$1', [owner.id]);
  await api.post('/api/admin/auth/logout', { headers: { origin } });
  console.log('PASS upload ownership, signed PUT/GET, MIME normalization, retry, metadata stripping and protected file access');

  const forged = Buffer.from('<svg><script>alert(1)</script></svg>');
  const forgery = (await (await reserve(payload(forged, 'fake.jpg', 'image/jpeg'))).json()).data;
  await api.put(forgery.url, { headers: forgery.headers, data: forged });
  assert.equal((await finalize(forgery.uploadId)).status(), 415);
  const mismatch = (await (await reserve({ ...payload(), sha256: '0'.repeat(64) })).json()).data;
  await api.put(mismatch.url, { headers: mismatch.headers, data: png });
  assert.equal((await finalize(mismatch.uploadId)).status(), 422);
  const heic = await readFile('tests/fixtures/example.heic');
  const heicTicket = (await (await reserve(payload(heic, '현장.heic', 'image/heic'))).json()).data;
  assert.ok((await api.put(heicTicket.url, { headers: heicTicket.headers, data: heic })).ok());
  const heicDone = await finalize(heicTicket.uploadId); assert.equal(heicDone.status(), 200, await heicDone.text());
  const large = await sharp(randomBytes(1700 * 1700 * 3), { raw: { width: 1700, height: 1700, channels: 3 } }).png().toBuffer();
  assert.ok(large.length > 4.5 * 1024 * 1024 && large.length < 10 * 1024 * 1024);
  const largeTicket = (await (await reserve(payload(large, 'large.png', 'image/png'))).json()).data;
  assert.ok((await api.put(largeTicket.url, { headers: largeTicket.headers, data: large })).ok());
  assert.equal((await finalize(largeTicket.uploadId)).status(), 200);
  const expired = (await (await reserve()).json()).data;
  await pool.query("UPDATE upload_tickets SET expires_at=now() - interval '1 second' WHERE id=$1", [expired.uploadId]);
  assert.equal((await finalize(expired.uploadId)).status(), 410);
  const stranger = await makeInquiry();
  assert.equal((await reserve(payload(), `/api/inquiries/${stranger.id}/attachments`, owner.key)).status(), 403);
  await pool.query("UPDATE inquiries SET created_at=now() - interval '31 minutes' WHERE id=$1", [stranger.id]);
  assert.equal((await reserve(payload(), `/api/inquiries/${stranger.id}/attachments`, stranger.key)).status(), 403);
  const crowded = await makeInquiry();
  const concurrent = await Promise.all(Array.from({ length: 11 }, () => reserve(payload(), `/api/inquiries/${crowded.id}/attachments`, crowded.key)));
  assert.equal(concurrent.filter(response => response.status() === 201).length, 10);
  assert.equal(concurrent.filter(response => response.status() === 409).length, 1);
  console.log('PASS forged bytes, checksum mismatch, HEIC, expired grants and concurrent ten-photo reservation limit');
}
