import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import { db } from '@/lib/db';
import { PublicShell } from '@/components/public/public-site';
import { inquiryTypeLabel } from '@/lib/admin-inquiry';
import { TrackView } from '@/components/public/analytics';
export const dynamic = 'force-dynamic';
export async function generateMetadata({ params }: PageProps<'/works/[slug]'>): Promise<Metadata> { const slug = (await params).slug; const work = await db().workCase.findFirst({ where: { slug, published: true, deletedAt: null }, select: { title: true, summary: true } }); return work ? { title: work.title, description: work.summary ?? 'OK소방 작업사례', alternates: { canonical: `/works/${slug}` }, openGraph: { title: `${work.title} | OK소방`, description: work.summary ?? 'OK소방 작업사례' } } : {}; }
export default async function WorkDetail({ params }: PageProps<'/works/[slug]'>) { const slug = (await params).slug; const work = await db().workCase.findFirst({ where: { slug, published: true, deletedAt: null }, select: { title: true, category: true, location: true, buildingType: true, workDate: true, summary: true, description: true } }); if (!work) notFound(); return <PublicShell><main><TrackView event="work_view" value={slug}/><section className="bg-slate-950 text-white"><div className="mx-auto max-w-5xl px-5 py-20 lg:px-8"><p className="text-sm font-bold tracking-widest text-red-400">{inquiryTypeLabel[work.category]}</p><h1 className="mt-5 text-4xl font-black sm:text-6xl">{work.title}</h1><p className="mt-6 text-lg leading-8 text-slate-300">{work.summary}</p></div></section><article className="mx-auto max-w-3xl px-5 py-16 lg:px-8"><dl className="grid gap-4 rounded-2xl bg-slate-100 p-6 sm:grid-cols-2"><div><dt className="text-xs font-bold text-slate-500">작업 지역</dt><dd className="mt-2 font-bold">{work.location ?? '비공개'}</dd></div><div><dt className="text-xs font-bold text-slate-500">건물 유형</dt><dd className="mt-2 font-bold">{work.buildingType ?? '현장별 상이'}</dd></div></dl><p className="mt-10 whitespace-pre-wrap leading-8 text-slate-700">{work.description}</p><Link href="/works" className="mt-10 inline-flex min-h-11 items-center font-bold text-red-700">← 작업사례 목록</Link></article></main></PublicShell>; }
